encoding: utf-8
# theme: jekyll-theme-cayman

title: Hayse Blog
description: notes for my left, study and works.
keywords: Blog,Notes
lang: zh-CN
author: Hayse
footerText: Used pure.css and jekyll with github.pages

# 菜单
menu:
  - title: 首页
    url: /
  - title: 归类
    url: /pages/categories.html
  - title: 搜索
    url: /pages/search.html
  - title: 友链
    url: /pages/links.html
  - title: 留言
    url: /pages/chat.html
  - title: 关于
    url: /pages/about.html

# 点击页面文字冒出特效,不需要请设置为false
extClickEffect: true





